### ISSUE TITLE
decodeURIComponent chokes on this url in chrome

### ISSUE THREAD

**Issue by QwertyCoolMT** [NickCarneiro/curlconverter#102]
`curl "http://gis.toronto.ca/arcgis/rest/services/primary/cot_geospatial2_mtm/MapServer/export?dpi=96^&transparent=true^&format=png8^&layers=show^%^3A-1^&bbox=313601.669163407^%^2C4836343.506132588^%^2C314154.6494360342^%^2C4836659.683848277^&bboxSR=2019^&imageSR=2019^&size=836^%^2C478^&f=image" -H "DNT: 1" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: en-US,en;q=0.9,en-GB;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" -H "Accept: image/webp,image/apng,image/*,*/*;q=0.8" -H "Referer: http://app.toronto.ca/DevelopmentApplications/mapSearchSetup.do?action=init" -H "Cookie: WEBTRENDS_ID=c3be777c.5780e59335841; WT_FPC=id=df56a12b-9622-4f45-aa84-5658ce947746:lv=1540325842589:ss=1540323185906; TS0196318c=01716c4681eafadcd231810d791f50d090d8221d6b3604100314f1f6337936ea946de1633db62835d0906bf1a2af7853bfceab2d34" -H "Connection: keep-alive" --compressed`

**Comment by NickCarneiro** [comment]
Node's implementation of `decodeURIComponent` can handle this but browsers cannot.

(todo link other related issues)


```
import requests

cookies = {
    'WEBTRENDS_ID': 'c3be777c.5780e59335841',
    'WT_FPC': 'id=df56a12b-9622-4f45-aa84-5658ce947746:lv=1540325842589:ss=1540323185906',
    'TS0196318c': '01716c4681eafadcd231810d791f50d090d8221d6b3604100314f1f6337936ea946de1633db62835d0906bf1a2af7853bfceab2d34',
}

headers = {
    'DNT': '1',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'en-US,en;q=0.9,en-GB;q=0.8',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
    'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8',
    'Referer': 'http://app.toronto.ca/DevelopmentApplications/mapSearchSetup.do?action=init',
    'Connection': 'keep-alive',
}

params = (
    ('dpi', '96^'),
    ('transparent', 'true^'),
    ('format', 'png8^'),
    ('layers', 'show^%%5E3A-1^'),
    ('bbox', '313601.669163407^%%5E2C4836343.506132588^%%5E2C314154.6494360342^%%5E2C4836659.683848277^'),
    ('bboxSR', '2019^'),
    ('imageSR', '2019^'),
    ('size', '836^%%5E2C478^'),
    ('f', 'image'),
)

response = requests.get('http://gis.toronto.ca/arcgis/rest/services/primary/cot_geospatial2_mtm/MapServer/export', headers=headers, params=params, cookies=cookies)

#NB. Original query string below. It seems impossible to parse and
#reproduce query strings 100% accurately so the one below is given
#in case the reproduced version is not "correct".
# response = requests.get('http://gis.toronto.ca/arcgis/rest/services/primary/cot_geospatial2_mtm/MapServer/export?dpi=96^&transparent=true^&format=png8^&layers=show^%^3A-1^&bbox=313601.669163407^%^2C4836343.506132588^%^2C314154.6494360342^%^2C4836659.683848277^&bboxSR=2019^&imageSR=2019^&size=836^%^2C478^&f=image', headers=headers, cookies=cookies)
```

**Comment by verhovsky** [comment]
Seeing the `^` in all the params

```
    ('dpi', '96^'),
    ('transparent', 'true^'),
    ('format', 'png8^'),
```

I think this is the same issue as #143, i.e. you copied as "`Copy as cURL (cmd)`" instead of clicking on the regular "Copy as cURL". `curlconverter` doesn't support cmd curl commands.
