### ISSUE TITLE
Error parsing curl command.

### ISSUE THREAD

**Issue by kaixin-bai** [NickCarneiro/curlconverter#106]
wenn i run this curl command, i get 'Error parsing curl command.'
curl -X PUT "http://169.254.6.230/api/v1/nodes/rc_itempick/services/compute_grasps" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{ \
    \"args\": { \
        \"pose_frame\": \"camera\", \
        \"suction_surface_length\": 0.02, \
        \"suction_surface_width\": 0.02 \
    } \
}"

the followed is what i write myself, but it works not good. Does anybody knows what is wrong?
import requests
url = "http://169.254.6.230/api/v1/nodes/rc_itempick/services/compute_grasps"
headers = {
    "accept": "application/json",
    "Content-Type": "pplication/json"
}
data = "{ \
            \"args\": { \
                \"pose_frame\": \"camera\", \
                \"suction_surface_length\": 0.02, \
                \"suction_surface_width\": 0.02 \
            } \
        }"
if __name__ == '__main__':
    resp = requests.get(url, headers=headers, data=data)
    # print(resp.status_code)
    # print(resp.content)
    print(resp.text)

**Comment by rchamarthi** [comment]
Can you change the double quotes around **data** to single quotes? Seems to be working fine, even without it, when I try on the UI. This is the output I see on https://curl.trillworks.com/

```
import requests

headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json',
}

data = '{ \nargs: { \npose_frame: camera, \nsuction_surface_length: 0.02, \nsuction_surface_width: 0.02 \n} \n}'

response = requests.put('http://169.254.6.230/api/v1/nodes/rc_itempick/services/compute_grasps', headers=headers, data=data)
```
