### ISSUE TITLE
parsing error in specific curl

### ISSUE THREAD

**Issue by yananet** [NickCarneiro/curlconverter#108]
Hello, following doesn't work...

```
curl -X GET "http://127.0.0.1:8001/api/groups/" -H  "accept: application/json" -H  "authorization: Basic SoMeCoOkIe" -H  "X-CSRFToken: SoMeToKeNvAlUe"
```

**Comment by cf512** [comment]
This was a head scratcher, but I now see the issue. It's the two spaces between -H and the values. With the extra spaces removed, it converts successfully. I'll update the parser to account for this.
