### ISSUE TITLE
The Urlencode by GBK data makes python convert wrong

### ISSUE THREAD

**Issue by liuxsdev** [NickCarneiro/curlconverter#110]
I found if there is something encoded by GBK(or other) in  --data ,python(and PHP R) convert will fail. But Go/Nodejs works fine.

![1](https://user-images.githubusercontent.com/11004456/49638706-f8e04400-fa43-11e8-86fa-718ec277eb49.png)
![2](https://user-images.githubusercontent.com/11004456/49638707-f8e04400-fa43-11e8-9e0b-c90bcd6cf9d1.png)

**Comment by verhovsky** [comment]
Closing because it seems to work now.

```sh
curl 'http://example.com' --data 'data=1&text=%D2%D4' --compressed
```

```py
import requests

data = {
  'data': '1',
  'text': '%D2%D4'
}

response = requests.post('http://example.com/', data=data)
```
