### ISSUE TITLE
[Test] Cannot Run tests on Windows 

### ISSUE THREAD

**Issue by Jay9596** [NickCarneiro/curlconverter#117]
Is there a way to run the tests on windows ?

**Comment by Jay9596** [comment]
Hi,

I was trying to add functionality, but I don't have a env to run bash script set up .
Can you explain what it does ?

The problem is while running `npm test` but running `node .\test.js` is fine.

**Comment by NickCarneiro** [comment]
```
#!/bin/bash
set -e
./node_modules/standard/bin/cmd.js index.js generators/*.js test.js *.js
./node_modules/tape/bin/tape test.js

```

This script is mainly here to make continuous integration work nicely by running the style checker and unit tests back-to-back. You can run the individual pieces on their own if you like.

The `cmd.js` command runs `standard` the js style checker. You can install standard globally and then just run `standard` with the same arguments.

The `tape` command runs the tests and produces a specific output format called TAP. (https://testanything.org/)

Like you mentioned, it's possible to just run `node test.js`. As far as I can tell the only benefit to using the `tape` binary directly is to get file name globbing, but we don't do that so it doesn't look like it actually helps us here! Just run the command you suggested.

If standard is too difficult to get working on windows just skip it and focus on the unit tests.

What kind of contribution were you thinking of making?

**Comment by Jay9596** [comment]
I was thinking of adding Rust language support #111 .
So I was testing and trying out how things work. 

My plan is to get some basic cases done and then send a PR.
Any suggestions or improvements ?

**Comment by NickCarneiro** [comment]
That would be awesome!

Don't be afraid to fix any bugs you find along the way.
