### ISSUE TITLE
Invalid Http Method Recognize

### ISSUE THREAD

**Issue by 1Z9N4IZ** [NickCarneiro/curlconverter#123]
- Problem occur will having convert curl to python
- curl
  curl -G endpoint 
--data key="key" 
--data url="url"

- python 
import requests
data = { 'key': key,  'url': url}
response = requests.post(endpoint, data=data)

-- Valid Response should be:
import requests
data = { 'key': key,  'url': url}
response = requests.get(endpoint, params=data)

**Comment by cf512** [comment]
I looked into this and it is converting properly now as GET. Please test when convenient. Closing this for now, but feel free to reopen if you still have this problem.
