### ISSUE TITLE
Error converting valid curl command to py

### ISSUE THREAD

**Issue by rosefei** [NickCarneiro/curlconverter#126]
curl -X POST "http://localhost:5000/forms/v1.0/dataset/1/score" -H  "accept: application/json" -H  "Content-Type: application/json-patch+json" -d "{  \"modelId\": 1}"

**Comment by Katzen88** [comment]
`import requests

headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json-patch+json',
}

data = '{ modelId: 1}'

response = requests.post('http://localhost:5000/forms/v1.0/dataset/1/score', headers=headers, data=data)
`

**Comment by rosefei** [comment]
I used this:  looks like you just need " " around the modelid.
# curl -X POST "http://localhost:5000/forms/v1.0/dataset/1/score" -H
"accept: application/json" -H "Content-Type: application/json-patch+json"
-d "{ \"modelId\": 1}"
hearders = {
'accept': 'application/json',
'Content-Type': 'application/json-patch+json'
}
data = '{"modelId": "1"}'
model = requests.post('http://localhost:5000/forms/v1.0/dataset/1/score',
headers=headers, data=data).json()


*Fei Guo *
+1 206.388.6438
http://about.me/rosefeiguo

**Comment by romadrutskii** [comment]
It works as expected, I don't see any problem here.
