### ISSUE TITLE
Error parsing curl command.

### ISSUE THREAD

**Issue by DipperStar** [NickCarneiro/curlconverter#129]
curl "http://ogoss.gameyw.netease.com/dwr/call/plaincall/Service.getData.dwr" -H "Origin: http://ogoss.gameyw.netease.com" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: zh-CN,zh;q=0.9" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" -H "Content-Type: text/plain" -H "Accept: */*" -H "Referer: http://ogoss.gameyw.netease.com/data/zqAdd.jsp" -H "Cookie: NETS_GS_AUTH=D3158F89BF19F68B656C301B5B1726FB6F828B3402A10100B95BA6FDBAE6DB1E73D26A7F51CBA7061E7A77F4C7D642AE3D6829AFEB84CA55AF45D02ED1139B3CE71E103FF2E135B2; _km_noosfero_session=BAh7BjoPc2Vzc2lvbl9pZCIlOWMxNzI5ZDY5MDNiMzMzYTZlNDdhYTc5YTk2NWI3MTg^%^3D--c65e460d2bc029911f2a9cefb9fcd85cad482a3d; _ntes_nnid=e06af79162ff524ce226cb2e944bd6ae,1556511038987; JSESSIONID=aaaDp4NNY-CtRdAYJESPw; NETS_GS_AUTH=D3158F89BF19F68B656C301B5B1726FB6F828B3402A10100B95BA6FDBAE6DB1E73D26A7F51CBA7061E7A77F4C7D642AE3D6829AFEB84CA55AF45D02ED1139B3CE71E103FF2E135B2" -H "Connection: keep-alive" --data-binary ^"callCount=1^

page=/data/zqAdd.jsp^

httpSessionId=aaaDp4NNY-CtRdAYJESPw^

scriptSessionId=E7DBC398A66133BEE8AD51EB0BF6CDFC784^

c0-scriptName=Service^

c0-methodName=getData^

c0-id=0^

c0-param0=string:zq_add^

c0-e1=string:game_server^%^3D10001^

c0-e2=string:qtitle^%^3D^%^E5^%^AE^%^A2^%^E6^%^9C^%^8DGM^%^E5^%^B8^%^AE^%^E6^%^82^%^A8^%^E5^%^88^%^9B^%^E5^%^BB^%^BA^%^E7^%^9A^%^84^%^E9^%^97^%^AE^%^E9^%^A2^%^98^

c0-e3=string:dianhua^%^3D11111^

c0-e4=string:sex^%^3D^

c0-e5=string:gmid^%^3DN5095-^%^E5^%^B0^%^B9^%^E6^%^81^%^92-^%^E5^%^A4^%^A7^%^E5^%^94^%^90^%^E9^%^95^%^87^%^E9^%^AD^%^94^%^E7^%^BB^%^84^

c0-e6=string:reply^%^3D^

c0-e7=string:remark^%^3D^

c0-e8=string:truename^%^3D^

c0-e9=string:pid^%^3D231^

c0-e10=string:urs^%^3Daebfukgal4vfhwi^%^40163.com^

c0-e11=string:game_uid^%^3DWijBGwc9pmElk8bl^

c0-e12=string:check_vip_account^%^3Daebfukgal4vfhwi^

c0-e13=string:callvip^%^3D^

c0-e14=string:upload_og^%^3D^

c0-e15=string:type_id^%^3D4209^

c0-e16=string:sid^%^3D4209^

c0-param1=Array:^[reference:c0-e1,reference:c0-e2,reference:c0-e3,reference:c0-e4,reference:c0-e5,reference:c0-e6,reference:c0-e7,reference:c0-e8,reference:c0-e9,reference:c0-e10,reference:c0-e11,reference:c0-e12,reference:c0-e13,reference:c0-e14,reference:c0-e15,reference:c0-e16^]^

c0-param2=boolean:false^

batchId=21^

^" --compressed

**Comment by verhovsky** [comment]
I think this is a duplicate of #143
