### ISSUE TITLE
Parsing error - "cookie: " became part of key in Python cookies-dict

### ISSUE THREAD

**Issue by johandicap** [NickCarneiro/curlconverter#135]
Hi Nick,

Great job with this curl converter! I ran into a small issue today, where a curl command worked in bash, but the Python-converted variant did not work due to a wrongly parsed header.

When converting the following curl cookie header to Python:

```
-H 'cookie: secure_user_id=InNlY3VyZTEwNjI3Ig%3D%3D--3b5df49345735791f2b80eddafb630cdcba76a1d; adaptive_image=1440; has_js=1; ccShowCookieIcon=no; _web_session=Y2h...e5'
```

It resulted in a cookies dict like this:

```
cookies = {
    'cookie: secure_user_id': 'InNlY3VyZTEwNjI3Ig%3D%3D--3b5df49345735791f2b80eddafb630cdcba76a1d',
    'adaptive_image': '1440',
    'has_js': '1',
    'ccShowCookieIcon': 'no',
    '_web_session': 'Y2h...e5',
}
```

that fails, rather than the following expected cookies dict that works:

```
cookies = {
    'secure_user_id': 'InNlY3VyZTEwNjI3Ig%3D%3D--3b5df49345735791f2b80eddafb630cdcba76a1d',
    'adaptive_image': '1440',
    'has_js': '1',
    'ccShowCookieIcon': 'no',
    '_web_session': 'Y2h...e5',
}
```

It seems to be a more or less simple parsing error where the "cookie: " erroneously became part of the dict key:

```
'cookie: secure_user_id': 'InNlY3VyZTEwNjI3Ig%3D%3D--3b5df49345735791f2b80eddafb630cdcba76a1d',
```

Where it should just have become:

```
'secure_user_id': 'InNlY3VyZTEwNjI3Ig%3D%3D--3b5df49345735791f2b80eddafb630cdcba76a1d',
```

Best regards,
Johan

**Comment by cf512** [comment]
Thanks @johandicap for reporting this. I have opened #153 which will fix this issue.

**Comment by johandicap** [comment]
You're welcome. Thanks for fixing it :)
