### ISSUE TITLE
Error parsing curl command.

### ISSUE THREAD

**Issue by JoergVanAken** [NickCarneiro/curlconverter#138]
The following curl command works fine in the command line but the converter does not accept it:

curl --proxy socks5://111.222.333.444:1080 --url 'smtp://smtp.office365.com:587' --ssl-reqd --mail-from 'a@b.com' --mail-rcpt 'c@b.com' --upload-file 'Mail.txt' --user 'a@b.com:password' --insecure

**Comment by cf512** [comment]
Hi there. Part of the problem seems to be due to the socks5 protocol not being accepted as valid by the parser. I can potentially add support for that. Some of the options in the input may need to be added to the converter as well. Happy to look into further. For now, could you advise what language you are wanting to convert this to? Thanks.

**Comment by wuujiann** [comment]
Looks like there is no support for socks5 or socks5h.  The following curl command is translated to dart code, but the proxy is totally ignored.
==> 'curl' command:
curl --proxy socks5h://10.200.11.250:1080 api.tls.ai:3000

==> translated 'dart' code 
import 'package:http/http.dart' as http;

void main() async {
  var res = await http.get('api.tls.ai:3000');
  if (res.statusCode != 200) throw Exception('get error: statusCode= ${res.statusCode}');
  print(res.body);
}

**Comment by csells** [comment]
Hey @wuujiann what code should be generated in this case?

**Comment by wuujiann** [comment]
@csells Thanks for your prompt reply.  I was looking for support of SOCKS5 proxy in dart's [http](https://pub.dev/packages/http) package.  I thought your curl parser would generate the SOCKS5 proxy code for dart.  Looks like SOCKS5 proxy is not supported in http package ([link](https://github.com/dart-lang/http/issues/65).  In any case, thanks very much for your help. :+1:

**Comment by csells** [comment]
I was able to find some proxy stuff listed here: https://api.dartlang.org/stable/2.5.0/dart-io/HttpClient/findProxyFromEnvironment.html

I don't know if this solves your problem.

**Comment by wuujiann** [comment]
Unfortunately, findProxy or findProxyFromEnvironment do not appear to have solved the problem.  
I tried setting HttpClient's findProxy property to the SOCKS5 proxy server (see code below).  But, it doesn't work.  I believe the current Proxy supported by HttpClient are only HTTP Proxy, not SOCKS5 proxy. 

client.findProxy = myProxy;
String myProxy(Uri uri) {
  return 'PROXY 10.200.11.250:1080;';
}

**Comment by csells** [comment]
Unfortunately if the underlying lib doesn't support it, I can't generate the code. : (
