### ISSUE TITLE
Error converting POST

### ISSUE THREAD

**Issue by vrst37** [NickCarneiro/curlconverter#139]
A valid command:

> curl -X POST "http://127.0.0.1:5000/V1/x" -H  "accept: application/json" -H  "Content-Type: application/x-www-form-urlencoded" -d "cid=1,2&gid=1,2&timestamp=1,2&dvl=1,2&con=1,2&pub=1,2&sub=1,2&new=1,2&inv=1,2"

**Comment by leovarmak** [comment]
@vrst37 What is the issue you are facing ?

**Comment by vrst37** [comment]
Very strange, it is working fine now. 
When I used it last, it said invalid.

**Comment by vrst37** [comment]
Something is not right. Here is what is happening on firefox and chrome:

> curl -X POST "http://127.0.0.1:5000/V1/company_message_frequency" -H  "accept: application/json" -H  "Content-Type: application/x-www-form-urlencoded" -d "cid=1,1&timestamp=1,1&messages=1,1"

Here is the screenshot:

![error_report](https://user-images.githubusercontent.com/34431050/62485788-8bbbb480-b772-11e9-80ff-e5f1cdab9099.png)

**Comment by leovarmak** [comment]
@vrst37 I just checked on both firefox and chrome and it works for me.

**Comment by vrst37** [comment]
Hello,
Here is the console output from my browser (Chrome)

![Screenshot from 2019-08-13 14-30-58](https://user-images.githubusercontent.com/34431050/62978864-23ef1480-bdd7-11e9-94bd-6185080b7448.png)

**Comment by romadrutskii** [comment]
can't reproduce
