### ISSUE TITLE
cookie  %  error  bug

### ISSUE THREAD

**Issue by 6897889** [NickCarneiro/curlconverter#140]
cookie cookie  %  error  bug

right cookie：
Cookie: think_language=zh-CN; acw_tc=707c9fda15632935923418477e097db14ecba77d08ff38e9ecda470d65c412; _ga=GA1.2.1797673890.1563293593; _gat=1; PHPSESSID=phpqaferk9dt0ccmj84ckjocu5; _gid=GA1.2.100326142.1563293602; yaozh_logintime=1563293966; yaozh_user=785402%09c510000735; yaozh_userId=785402; yaozh_uidhas=1; yaozh_mylogin=1563293966; Hm_lpvt_65968db3ac154c3089d7f9a4cbb98c94=1563293967; acw_tc=707c9fda15632935923418477e097db14ecba77d08ff38e9ecda470d65c412; Hm_lvt_65968db3ac154c3089d7f9a4cbb98c94=1563293593%2C1563293967; MEIQIA_VISIT_ID=1O6UzlrjYS9LD0xYdj4ayfm6DZB; MEIQIA_VISIT_ID=1O6UzlrjYS9LD0xYdj4ayfm6DZB

error cookie ：

cookies = {
    'think_language': 'zh-CN',
    'acw_tc': '707c9fda15632935923418477e097db14ecba77d08ff38e9ecda470d65c412',
    '_ga': 'GA1.2.1797673890.1563293593',
    '_gat': '1',
    'PHPSESSID': 'phpqaferk9dt0ccmj84ckjocu5',
    '_gid': 'GA1.2.100326142.1563293602',
    'yaozh_logintime': '1563293966',
    'yaozh_user': '785402^%^09c510000735',
    'yaozh_userId': '785402',
    'yaozh_uidhas': '1',
    'yaozh_mylogin': '1563293966',
    'Hm_lpvt_65968db3ac154c3089d7f9a4cbb98c94': '1563293967',
    'Hm_lvt_65968db3ac154c3089d7f9a4cbb98c94': '1563293593^%^2C1563293967',
    'MEIQIA_VISIT_ID': '1O6UzlrjYS9LD0xYdj4ayfm6DZB',
}

^%^2（error）  %（right）

**Comment by cf512** [comment]
Hi there. I am trying to replicate this but haven't been able to yet. Could you please send some more details? i.e. full curl input, or screenshots, or your code where this issue is occurring, or replication steps, etc. Thanks.

**Comment by romadrutskii** [comment]
> ^%^2（error） %（right）

@6897889 I guess, the issue has been fixed. Parses without `^`.
