### ISSUE TITLE
Error parsing curl command.

### ISSUE THREAD

**Issue by iamdaguduizhang** [NickCarneiro/curlconverter#166]
curl 'https://s.1688.com/company/company_search.htm?keywords=%C6%FB%B3%B5&n=y&netType=1%2C11&spm=a260k.dacugeneral%2Fnew.search.0' -H 'authority: s.1688.com' -H 'cache-control: max-age=0' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36' -H 'sec-fetch-mode: navigate' -H 'sec-fetch-user: ?1' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'sec-fetch-site: none' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: zh-CN,zh;q=0.9' -H 'cookie: cna=zqu8FGo3tQACAWVEROown73f; ali_apache_id=11.27.146.52.154986650175.410353.8; ali_ab=101.68.68.234.1551952961093.8; lid=sp%E4%B9%88%E4%B9%88%E5%93%92214; ali_apache_track=c_mid=b2b-30255702317c68f|c_lid=sp%E4%B9%88%E4%B9%88%E5%93%92214|c_ms=1; cookie2=146f7a6922bccf66535d3e78f9fd815d; hng=CN%7Czh-CN%7CCNY%7C156; t=11cff45c72004287dbc7d7f445b6ddd2; _tb_token_=f4eadb18605be; __cn_logon__=false; h_keys="%u6c7d%u8f66#%u5c0f%u7c73"; alisw=swIs1200%3D1%7C; alicnweb=homeIdttS%3D92877635209548718074379840853382764800%7Ctouch_tb_at%3D1568099210736%7ChomeIdttSAction%3Dtrue%7Clastlogonid%3Dsp%25E4%25B9%2588%25E4%25B9%2588%25E5%2593%2592214; ad_prefer="2019/09/10 15:11:47"; isg=BHl5Eq2TAB-L7N2dHojcged7iOVZTmN4WMQuApuu8aAfIpm049fBCNlwoGZxoQVw; l=cBNTeJrqvoue-lN2XOCaourza779IIRYjuPzaNbMi_5ha68_HRbOkz0g6FJ6cjWdOgLB4rRpHn99-etkql5PvK9PJA6P.' --compressed

**Comment by jgroom33** [comment]
please narrow this down to the specific item that is cause the failure (remove the headers and other props one at a time till the error persists and the curl command is succinct)

**Comment by turbinenreiter** [comment]
Facing the same issue - `-H` is what seems to break it.

**Comment by clintonc** [comment]
I can't reproduce this by just copy-pasting the command.  I checked that a unit test based on this example passes:

https://github.com/clintonc/curlconverter/commit/d1ee1a13c79e4fb0f05cc74b7ce4503336aabd24

Can you give some more information here?

**Comment by turbinenreiter** [comment]
On https://curl.trillworks.com/ this:

`curl -X POST "https://bal.blab.la" -H  "Content-Type: application/json"`

returns: Error parsing curl command.

![Screenshot from 2019-10-13 17-59-10](https://user-images.githubusercontent.com/3295964/66718351-3db2d500-ede3-11e9-95f4-b7a45ad79438.png)

Tried both Firefox and Chrome.

The JavaScript console error:

```
TypeError: "header.indexOf is not a function"
    parseHeaders https://curl.trillworks.com/scripts/main.min.js:1
    parseHeaders https://curl.trillworks.com/scripts/main.min.js:1
    parseCurlCommand https://curl.trillworks.com/scripts/main.min.js:1
    toPython https://curl.trillworks.com/scripts/main.min.js:1
    convert https://curl.trillworks.com/scripts/main.min.js:1
main.min.js:1:192262
```

The original example from @iamdaguduizhang also has the same error. Since the unit test passes, what is on the web version that the unit test doesn't test?

**Comment by jgroom33** [comment]
Missing double quote at the end

**Comment by jgroom33** [comment]
i tried on chrome and am not able to reproduce (even with omitting the double quote)

**Comment by jgroom33** [comment]
i deleted comments that were a different behavior.  The behavior above is cause by url decode issues.
The encoding used in the above is not utf-8.

This works(no encoding):
```
curl https://s.1688.com/company/company_search.htm?keywords=Æû³µ
```

This works(utf-encoded):
```
curl https://s.1688.com/company/company_search.htm?keywords=Æû³%C2%B5
```

the decoding is not being handled.

Perhaps there are similar behaviors with something in the headers.

... not sure whether this is a defect or user error
