### ISSUE TITLE
i am getting error in this code

### ISSUE THREAD

**Issue by biggersmilesj** [NickCarneiro/curlconverter#174]
curl "https://www.facebook.com/tr/?id=894647383888112^&ev=SubscribedButtonClick^&dl=https^%^3A^%^2F^%^2Fwww.oyorooms.com^%^2Flogin^%^3Fcountry^%^3D^%^26retUrl^%^3D^%^2F^&rl=https^%^3A^%^2F^%^2Fwww.google.com^%^2F^&if=false^&ts=1571313171473^&cd^\[buttonFeatures^\]=^%^7B^%^22classList^%^22^%^3A^%^22loginCard__button^%^22^%^2C^%^22destination^%^22^%^3A^%^22^%^22^%^2C^%^22id^%^22^%^3A^%^22^%^22^%^2C^%^22imageUrl^%^22^%^3A^%^22^%^22^%^2C^%^22innerText^%^22^%^3A^%^22Verify^%^20Number^%^22^%^2C^%^22numChildButtons^%^22^%^3A0^%^2C^%^22tag^%^22^%^3A^%^22button^%^22^%^2C^%^22name^%^22^%^3A^%^22^%^22^%^2C^%^22value^%^22^%^3A^%^22^%^22^%^7D^&cd^\[buttonText^\]=Verify^%^20Number^&cd^\[formFeatures^\]=^%^5B^%^5D^&cd^\[pageFeatures^\]=^%^7B^%^22title^%^22^%^3A^%^22Hotel^%^20Booking^%^20India^%^2C^%^20Branded^%^20hotels^%^2C^%^20Affordable^%^20Stays^%^20-^%^20OYO^%^22^%^7D^&cd^\[parameters^\]=^%^5B^%^5D^&sw=1920^&sh=1080^&v=2.9.6^&r=stable^&ec=4^&o=30^&fbp=fb.1.1571313132822.713176453^&it=1571313132526^&coo=false^&es=automatic^&rqm=GET" -H "Sec-Fetch-Mode: no-cors" -H "Referer: https://www.oyorooms.com/login?country=^&retUrl=/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" --compressed &
curl "https://www.oyorooms.com/api/pwa/generateotp?phone=8200374673^&country_code=^%^2B91^&nod=4^&locale=en" -H "sec-fetch-mode: cors" -H "accept-encoding: gzip, deflate, br" -H "accept-language: en-US,en;q=0.9" -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" -H "accept: */*" -H "referer: https://www.oyorooms.com/login?country=^&retUrl=/" -H "authority: www.oyorooms.com" -H "cookie: _csrf=eoGczxsfpzWY0UH3Lv9CHZE0; acc=IN; mab=5d86c3fe28e3e42b50884b398f52007f; expd=j^%^3A^%^7B^%^22mwen^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^225^%^22^%^7D^%^2C^%^22phbb^%^22^%^3A^%^7B^%^22val^%^22^%^3A0^%^2C^%^22v^%^22^%^3A1^%^7D^%^2C^%^22shel^%^22^%^3A^%^7B^%^22val^%^22^%^3A0^%^2C^%^22v^%^22^%^3A1^%^7D^%^2C^%^22weng^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^220^%^22^%^2C^%^22v^%^22^%^3A^%^224^%^22^%^7D^%^2C^%^22bann^%^22^%^3A^%^7B^%^22val^%^22^%^3A0^%^2C^%^22v^%^22^%^3A1^%^7D^%^2C^%^22sold^%^22^%^3A^%^7B^%^22val^%^22^%^3A0^%^2C^%^22v^%^22^%^3A1^%^7D^%^2C^%^22otp4^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^222^%^22^%^7D^%^2C^%^22dwep^%^22^%^3A^%^7B^%^22val^%^22^%^3A0^%^2C^%^22v^%^22^%^3A1^%^7D^%^2C^%^22a2hs^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^222^%^22^%^7D^%^2C^%^22aowt^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^225^%^22^%^7D^%^2C^%^22mww2^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^224^%^22^%^7D^%^2C^%^22brch^%^22^%^3A^%^7B^%^22val^%^22^%^3A0^%^2C^%^22v^%^22^%^3A1^%^7D^%^2C^%^22hbad^%^22^%^3A^%^7B^%^22val^%^22^%^3A0^%^2C^%^22v^%^22^%^3A1^%^7D^%^2C^%^22dwhp^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^220^%^22^%^2C^%^22v^%^22^%^3A^%^225^%^22^%^7D^%^2C^%^22pppp^%^22^%^3A^%^7B^%^22val^%^22^%^3A0^%^2C^%^22v^%^22^%^3A1^%^7D^%^2C^%^22BnTc^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^220^%^22^%^2C^%^22v^%^22^%^3A^%^221^%^22^%^7D^%^2C^%^22mwql^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^221^%^22^%^7D^%^2C^%^22ndlp^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^225^%^22^%^7D^%^2C^%^22near^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^220^%^22^%^2C^%^22v^%^22^%^3A^%^222^%^22^%^7D^%^2C^%^22mnlp^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^223^%^22^%^7D^%^2C^%^22hind^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^220^%^22^%^2C^%^22v^%^22^%^3A^%^223^%^22^%^7D^%^2C^%^22bcpw^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^221^%^22^%^7D^%^2C^%^22gmmw^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^221^%^22^%^2C^%^22v^%^22^%^3A^%^221^%^22^%^7D^%^2C^%^22ioab^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^220^%^22^%^2C^%^22v^%^22^%^3A^%^222^%^22^%^7D^%^2C^%^22mhdp^%^22^%^3A^%^7B^%^22val^%^22^%^3A^%^220^%^22^%^2C^%^22v^%^22^%^3A^%^221^%^22^%^7D^%^7D; _uuid=dUxaRnA5NWJyWFlQYkpQNnEtemo6bzdvX01KLUNFbnRyS3hfdEgyLUE^%^3D; _uid=Not^%^20logged^%^20in; XSRF-TOKEN=jKt8YAKQ-6klFaz9EtvJ462cO0M6GDjes_XY; connect.sid=s^%^3ARvAHZhvQT4V7ysEV_-Xdby9OOlxEhdSZ.J2n1EBgYViHygTUGglnKbX2tejJUrHRwrMmVBQbFoFk; fingerprint2=f9ffcabc5824f3712af02e433cdb991b; AMP_TOKEN=^%^24NOT_FOUND; _ga=GA1.2.608130126.1571313130; _gid=GA1.2.449921091.1571313130; _gat=1; tvc_heatmap=enabled; _fbp=fb.1.1571313132822.713176453; tvc_sm_lpc=google^%^7Corganic^%^20/^%^20undefined; tvc_clicksInfo=/login?country=^&retUrl=/^|1" -H "sec-fetch-site: same-origin" -H "xsrf-token: jKt8YAKQ-6klFaz9EtvJ462cO0M6GDjes_XY" --compressed &
curl "https://bat.bing.com/bat.js" -H "Sec-Fetch-Mode: no-cors" -H "Referer: https://www.oyorooms.com/login?country=^&modal=signin^&retUrl=^%^2F" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" --compressed &
curl "https://www.google-analytics.com/collect?v=1^&_v=j79^&a=1602755778^&t=event^&_s=13^&dl=https^%^3A^%^2F^%^2Fwww.oyorooms.com^%^2F^&dr=https^%^3A^%^2F^%^2Fwww.google.com^%^2F^&dp=^%^2Flogin^&ul=en-us^&de=UTF-8^&dt=login^&sd=24-bit^&sr=1920x1080^&vp=1913x947^&je=0^&ec=lpc_tracking^&ea=lpc_source^%^2Fmedium^&_u=aHBAAEIJAAQC~^&jid=^&gjid=^&cid=608130126.1571313130^&tid=UA-52365165-1^&_gid=449921091.1571313130^&cd149=en^&cd1=India^&cd57=b^&cd62=a^&cd60=a^&cd61=a^&cd115=c^&cd116=a^&cd125=a^&cd127=b^&cd25=login^%^20Page^&cd88=^%^2Flogin^&cd89=200^&cd22=Thu^%^20Oct^%^2017^%^202019^%^2017^%^3A22^%^3A29^%^20GMT^%^2B0530^%^20(India^%^20Standard^%^20Time)^&cd99=mwen^%^235^%^3A1^%^7Cphbb^%^231^%^3A0^%^7Cshel^%^231^%^3A0^%^7Cweng^%^234^%^3A0^%^7Cbann^%^231^%^3A0^%^7Csold^%^231^%^3A0^%^7Cotp4^%^232^%^3A1^%^7Cdwep^%^231^%^3A0^%^7Ca2hs^%^232^%^3A1^%^7Caowt^%^235^%^3A1^%^7Cmww2^%^234^%^3A1^%^7Cbrch^%^231^%^3A0^%^7Chbad^%^231^%^3A0^%^7Cdwhp^%^235^%^3A0^%^7Cpppp^%^231^%^3A0^%^7CBnTc^%^231^%^3A0^%^7Cmwql^%^231^%^3A1^%^7Cndlp^%^235^%^3A1^%^7Cnear^%^232^%^3A0^%^7Cmnlp^%^233^%^3A1^%^7Chind^%^233^%^3A0^%^7Cbcpw^%^231^%^3A1^%^7Cgmmw^%^231^%^3A1^%^7Cioab^%^232^%^3A0^%^7Cmhdp^%^231^%^3A0^%^7C^&cd135=NA^&cd136=mwen^%^235^%^3A1^%^7Cphbb^%^231^%^3A0^%^7Cshel^%^231^%^3A0^%^7Cweng^%^234^%^3A0^%^7Cbann^%^231^%^3A0^%^7Csold^%^231^%^3A0^%^7Cotp4^%^232^%^3A1^%^7Cdwep^%^231^%^3A0^%^7Ca2hs^%^232^%^3A1^%^7Caowt^%^235^%^3A1^%^7Cmww2^%^234^%^3A1^%^7Cbrch^%^231^%^3A0^%^7Chbad^%^231^%^3A0^%^7Cdwhp^%^235^%^3A0^%^7Cpppp^%^231^%^3A0^%^7CBnTc^%^231^%^3A0^%^7Cmwql^%^231^%^3A1^%^7Cndlp^%^235^%^3A1^%^7Cnear^%^232^%^3A0^%^7Cmnlp^%^233^%^3A1^%^7Chind^%^233^%^3A0^%^7Cbcpw^%^231^%^3A1^%^7Cgmmw^%^231^%^3A1^%^7Cioab^%^232^%^3A0^%^7Cmhdp^%^231^%^3A0^%^7C^&cd73=false^&cd85=false^&cd120=false^&cd117=f9ffcabc5824f3712af02e433cdb991b^&cd147=NA^&cd100=Not^%^20logged^%^20in^&cd101=Not^%^20logged^%^20in^&cd102=Not^%^20logged^%^20in^&cd93=NA^&cd148=b^&cd74=Delhi^%^2CGurgaon^%^2CNoida^%^2CMumbai^%^2CBangalore^%^2CGoa^%^2CChennai^%^2CHyderabad^%^2CKolkata^%^2CJaipur^&cd37=608130126.1571313130^&cd143=google^%^257Corganic^%^2520^%^2F^%^2520undefined^%^20^%^2F^%^20undefined^&cd144=google^%^257Corganic^%^2520^%^2F^%^2520undefined^%^20^%^2F^%^20undefined^&cd140=^&z=2116090648" -H "Sec-Fetch-Mode: no-cors" -H "Referer: https://www.oyorooms.com/login?country=^&modal=signin^&retUrl=^%^2F" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" --compressed &
curl "https://www.facebook.com/tr/?id=894647383888112^&ev=PageView^&dl=https^%^3A^%^2F^%^2Fwww.oyorooms.com^%^2Flogin^%^3Fcountry^%^3D^%^26modal^%^3Dsignin^%^26retUrl^%^3D^%^252F^&rl=https^%^3A^%^2F^%^2Fwww.google.com^%^2F^&if=false^&ts=1571313171700^&sw=1920^&sh=1080^&v=2.9.6^&r=stable^&ec=5^&o=30^&fbp=fb.1.1571313132822.713176453^&it=1571313132526^&coo=false^&rqm=GET" -H "Sec-Fetch-Mode: no-cors" -H "Referer: https://www.oyorooms.com/login?country=^&modal=signin^&retUrl=^%^2F" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" --compressed &
curl "https://www.google-analytics.com/collect?v=1^&_v=j79^&a=1602755778^&t=pageview^&_s=14^&dl=https^%^3A^%^2F^%^2Fwww.oyorooms.com^%^2F^&dr=https^%^3A^%^2F^%^2Fwww.google.com^%^2F^&dp=^%^2FOTP^&ul=en-us^&de=UTF-8^&dt=Login^&sd=24-bit^&sr=1920x1080^&vp=1913x947^&je=0^&_u=aHBAAEIJAAQC~^&jid=^&gjid=^&cid=608130126.1571313130^&tid=UA-52365165-1^&_gid=449921091.1571313130^&cd149=en^&cd1=India^&cd57=b^&cd62=a^&cd60=a^&cd61=a^&cd115=c^&cd116=a^&cd125=a^&cd127=b^&cd25=login^%^20Page^&cd88=^%^2Flogin^&cd89=200^&cd22=Thu^%^20Oct^%^2017^%^202019^%^2017^%^3A22^%^3A51^%^20GMT^%^2B0530^%^20(India^%^20Standard^%^20Time)^&cd99=mwen^%^235^%^3A1^%^7Cphbb^%^231^%^3A0^%^7Cshel^%^231^%^3A0^%^7Cweng^%^234^%^3A0^%^7Cbann^%^231^%^3A0^%^7Csold^%^231^%^3A0^%^7Cotp4^%^232^%^3A1^%^7Cdwep^%^231^%^3A0^%^7Ca2hs^%^232^%^3A1^%^7Caowt^%^235^%^3A1^%^7Cmww2^%^234^%^3A1^%^7Cbrch^%^231^%^3A0^%^7Chbad^%^231^%^3A0^%^7Cdwhp^%^235^%^3A0^%^7Cpppp^%^231^%^3A0^%^7CBnTc^%^231^%^3A0^%^7Cmwql^%^231^%^3A1^%^7Cndlp^%^235^%^3A1^%^7Cnear^%^232^%^3A0^%^7Cmnlp^%^233^%^3A1^%^7Chind^%^233^%^3A0^%^7Cbcpw^%^231^%^3A1^%^7Cgmmw^%^231^%^3A1^%^7Cioab^%^232^%^3A0^%^7Cmhdp^%^231^%^3A0^%^7C^&cd135=NA^&cd136=mwen^%^235^%^3A1^%^7Cphbb^%^231^%^3A0^%^7Cshel^%^231^%^3A0^%^7Cweng^%^234^%^3A0^%^7Cbann^%^231^%^3A0^%^7Csold^%^231^%^3A0^%^7Cotp4^%^232^%^3A1^%^7Cdwep^%^231^%^3A0^%^7Ca2hs^%^232^%^3A1^%^7Caowt^%^235^%^3A1^%^7Cmww2^%^234^%^3A1^%^7Cbrch^%^231^%^3A0^%^7Chbad^%^231^%^3A0^%^7Cdwhp^%^235^%^3A0^%^7Cpppp^%^231^%^3A0^%^7CBnTc^%^231^%^3A0^%^7Cmwql^%^231^%^3A1^%^7Cndlp^%^235^%^3A1^%^7Cnear^%^232^%^3A0^%^7Cmnlp^%^233^%^3A1^%^7Chind^%^233^%^3A0^%^7Cbcpw^%^231^%^3A1^%^7Cgmmw^%^231^%^3A1^%^7Cioab^%^232^%^3A0^%^7Cmhdp^%^231^%^3A0^%^7C^&cd73=false^&cd85=false^&cd120=false^&cd117=f9ffcabc5824f3712af02e433cdb991b^&cd147=NA^&cd100=Not^%^20logged^%^20in^&cd101=Not^%^20logged^%^20in^&cd102=Not^%^20logged^%^20in^&cd93=NA^&cd148=b^&cd74=Delhi^%^2CGurgaon^%^2CNoida^%^2CMumbai^%^2CBangalore^%^2CGoa^%^2CChennai^%^2CHyderabad^%^2CKolkata^%^2CJaipur^&cd37=608130126.1571313130^&cd140=^&z=480478138" -H "Sec-Fetch-Mode: no-cors" -H "Referer: https://www.oyorooms.com/login?country=^&modal=signin^&retUrl=^%^2F" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" --compressed &
curl "https://www.google-analytics.com/collect?v=1^&_v=j79^&a=1602755778^&t=event^&_s=15^&dl=https^%^3A^%^2F^%^2Fwww.oyorooms.com^%^2F^&dr=https^%^3A^%^2F^%^2Fwww.google.com^%^2F^&dp=^%^2FOTP^&ul=en-us^&de=UTF-8^&dt=Login^&sd=24-bit^&sr=1920x1080^&vp=1913x947^&je=0^&ec=Signup^%^202^%^20page^&ea=Page^%^20Open^&el=Login^&_u=aHBAAEIJAAQC~^&jid=^&gjid=^&cid=608130126.1571313130^&tid=UA-52365165-1^&_gid=449921091.1571313130^&cd149=en^&cd1=India^&cd57=b^&cd62=a^&cd60=a^&cd61=a^&cd115=c^&cd116=a^&cd125=a^&cd127=b^&cd25=login^%^20Page^&cd88=^%^2Flogin^&cd89=200^&cd22=Thu^%^20Oct^%^2017^%^202019^%^2017^%^3A22^%^3A51^%^20GMT^%^2B0530^%^20(India^%^20Standard^%^20Time)^&cd99=mwen^%^235^%^3A1^%^7Cphbb^%^231^%^3A0^%^7Cshel^%^231^%^3A0^%^7Cweng^%^234^%^3A0^%^7Cbann^%^231^%^3A0^%^7Csold^%^231^%^3A0^%^7Cotp4^%^232^%^3A1^%^7Cdwep^%^231^%^3A0^%^7Ca2hs^%^232^%^3A1^%^7Caowt^%^235^%^3A1^%^7Cmww2^%^234^%^3A1^%^7Cbrch^%^231^%^3A0^%^7Chbad^%^231^%^3A0^%^7Cdwhp^%^235^%^3A0^%^7Cpppp^%^231^%^3A0^%^7CBnTc^%^231^%^3A0^%^7Cmwql^%^231^%^3A1^%^7Cndlp^%^235^%^3A1^%^7Cnear^%^232^%^3A0^%^7Cmnlp^%^233^%^3A1^%^7Chind^%^233^%^3A0^%^7Cbcpw^%^231^%^3A1^%^7Cgmmw^%^231^%^3A1^%^7Cioab^%^232^%^3A0^%^7Cmhdp^%^231^%^3A0^%^7C^&cd135=NA^&cd136=mwen^%^235^%^3A1^%^7Cphbb^%^231^%^3A0^%^7Cshel^%^231^%^3A0^%^7Cweng^%^234^%^3A0^%^7Cbann^%^231^%^3A0^%^7Csold^%^231^%^3A0^%^7Cotp4^%^232^%^3A1^%^7Cdwep^%^231^%^3A0^%^7Ca2hs^%^232^%^3A1^%^7Caowt^%^235^%^3A1^%^7Cmww2^%^234^%^3A1^%^7Cbrch^%^231^%^3A0^%^7Chbad^%^231^%^3A0^%^7Cdwhp^%^235^%^3A0^%^7Cpppp^%^231^%^3A0^%^7CBnTc^%^231^%^3A0^%^7Cmwql^%^231^%^3A1^%^7Cndlp^%^235^%^3A1^%^7Cnear^%^232^%^3A0^%^7Cmnlp^%^233^%^3A1^%^7Chind^%^233^%^3A0^%^7Cbcpw^%^231^%^3A1^%^7Cgmmw^%^231^%^3A1^%^7Cioab^%^232^%^3A0^%^7Cmhdp^%^231^%^3A0^%^7C^&cd73=false^&cd85=false^&cd120=false^&cd117=f9ffcabc5824f3712af02e433cdb991b^&cd147=NA^&cd100=Not^%^20logged^%^20in^&cd101=Not^%^20logged^%^20in^&cd102=Not^%^20logged^%^20in^&cd93=NA^&cd148=b^&cd74=Delhi^%^2CGurgaon^%^2CNoida^%^2CMumbai^%^2CBangalore^%^2CGoa^%^2CChennai^%^2CHyderabad^%^2CKolkata^%^2CJaipur^&cd37=608130126.1571313130^&cd140=^&z=1654524408" -H "Sec-Fetch-Mode: no-cors" -H "Referer: https://www.oyorooms.com/login?country=^&modal=signin^&retUrl=^%^2F" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" --compressed &
curl "https://bat.bing.com/action/0?ti=5256982^&Ver=2^&mid=370e1aae-aa80-68a1-f082-fccdce0fde3d^&pi=1200101525^&lg=en-US^&sw=1920^&sh=1080^&sc=24^&tl=Hotel^%^20Booking^%^20India,^%^20Branded^%^20hotels,^%^20Affordable^%^20Stays^%^20-^%^20OYO^&kw=OYO^%^20Rooms,^%^20OYO^%^20Hotels,^%^20OYO^%^20Inn,^%^20Budget^%^20Hotels,^%^20Guest^%^20House,^%^20Budget^%^20Hotels^%^20in^%^20Gurgaon,^%^20Guest^%^20House^%^20in^%^20Gurgaon,^%^20Budget^%^20Hotels^%^20in^%^20Delhi,^%^20Guest^%^20House^%^20in^%^20Delhi,^%^20Budget^%^20Hotels^%^20in^%^20Noida,^%^20Guest^%^20House^%^20in^%^20Noida,^%^20Budget^%^20Hotels^%^20in^%^20Bangalore,^%^20Guest^%^20House^%^20in^%^20Bangalore,^%^20Budget^%^20Hotels^%^20in^%^20Mumbai,^%^20Guest^%^20House^%^20in^%^20Mumbai,^%^20Cheap^%^20Hotels^%^20in^%^20Delhi,^%^20Cheap^%^20Hotels^%^20in^%^20Gurgaon,^%^20Cheap^%^20Hotels^%^20in^%^20Noida,^%^20Cheap^%^20Hotels^%^20in^%^20Bangalore,^%^20Cheap^%^20Hotels^%^20in^%^20Mumbai^&p=https^%^3A^%^2F^%^2Fwww.oyorooms.com^%^2Flogin^%^3Fcountry^%^3D^%^26modal^%^3Dsignin^%^26retUrl^%^3D^%^252F^&r=https^%^3A^%^2F^%^2Fwww.google.com^%^2F^&lt=4596^&evt=pageLoad^&msclkid=N^&rn=285559" -H "Sec-Fetch-Mode: no-cors" -H "Referer: https://www.oyorooms.com/login?country=^&modal=signin^&retUrl=^%^2F" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" --compressed

**Comment by verhovsky** [comment]
You pressed "Copy as cURL (cmd)" instead of "Copy as cURL (bash)". Duplicate of #143
