### ISSUE TITLE
Error on converting following but works from terminal

### ISSUE THREAD

**Issue by Cizor** [NickCarneiro/curlconverter#179]
curl -kd @freak.xml -H  x-ex-eex:1234 --cert ./lop.crt --key ./lop.key https://example.ex.com/exbr/tbr15?type=abCD

I can fire this curl from my terminal but it doesn't convert to python using this tool with error "Error parsing curl command."

I have changed tag names as they are for internal usage.

[freak.xml.zip](https://github.com/NickCarneiro/curlconverter/files/3845746/freak.xml.zip)

**Comment by jgroom33** [comment]
no errors are thrown.  whats the issue?
![image](https://user-images.githubusercontent.com/3970574/68905267-d5b31f80-06fd-11ea-8b77-2bf02c6aa18f.png)

**Comment by Cizor** [comment]
I am not sure how it is working now but I tried a lot on same day and it wasn't working. 
But since it is working as expected, closing this issue. 
Thanks for your help!!
