### ISSUE TITLE
Error: Invalid URI "httpbin.org/test"

### ISSUE THREAD

**Issue by wll8** [NickCarneiro/curlconverter#188]
## Error: Invalid URI "httpbin.org/test"
``` sh
bash-3.2$ curl httpbin.org/test
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

``` js
var request = require('request');

var options = {
    url: 'httpbin.org/test'
};

function callback(error, response, body) {
    console.log('error', error) // Error: Invalid URI "httpbin.org/test"
    if (!error && response.statusCode == 200) {
        console.log(body);
    }
}

request(options, callback);
```

**Comment by jgroom33** [comment]
I'd suggest checking to see how python requests lib handles this. I suspect the behavior might be implemented there:
https://github.com/pypa/warehouse/blob/master/tests/unit/utils/test_http.py

**Comment by wll8** [comment]
> I'd suggest checking to see how python requests lib handles this. I suspect the behavior might be implemented there:
> https://github.com/pypa/warehouse/blob/master/tests/unit/utils/test_http.py

Just need to be consistent with `curl` behavior

**Comment by jgroom33** [comment]
If possible, I think this fix is better implemented in the upstream library.

It can be fixed here with some modifications to this:
https://github.com/NickCarneiro/curlconverter/blob/master/generators/python.js#L149

The problem is the uri starts with http.
