### ISSUE TITLE
JSHint “Path must be a string” on Node 6

### ISSUE THREAD

**Issue by trdarr** [NickCarneiro/curlconverter#19]
https://travis-ci.org/trdarr/curlconverter/jobs/129091249

```
Running "jshint:gruntfile" (jshint) task
Warning: Path must be a string. Received null Use --force to continue.
```

**Comment by NickCarneiro** [comment]
How did you make travis build on node 6? I don't see the option.

**Comment by trdarr** [comment]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Available-Versions

```yaml
---
node_js:
  - '6'
```

**Comment by NickCarneiro** [comment]
Thanks, tr.

This particular issue has been resolved by removing jshint, and future builds will include node 6.

**Comment by trdarr** [comment]
👍
