### ISSUE TITLE
wrong syntax

### ISSUE THREAD

**Issue by akrsnr** [NickCarneiro/curlconverter#192]
I'm sure the following is given by the system I use, but not parsed.

`curl -X GET 'hqwwqwt/' -H  'accept: application/json' -H  'Authorization: 123456789'`

**Comment by romadrutskii** [comment]
> 
> 
> I'm sure the following is given by the system I use, but not parsed.
> 
> `curl -X GET 'hqwwqwt/' -H 'accept: application/json' -H 'Authorization: 123456789'`

I guess, the issue has been fixed. Parsed for every language.
