### ISSUE TITLE
Add generator for Swift (Alamofire)

### ISSUE THREAD

**Issue by ezefranca** [NickCarneiro/curlconverter#20]
Hi, I'm not a Javascript developer, but sometimes I coding small things in python and javascript and this project is fucking awesome. 

I'm a iOS developer, and looking this project, I was thinking if is possible generate the request in Swift using (https://github.com/Alamofire/Alamofire) for example. 

If you have a start point for me in your code to study and begin with this I appreciate.

(sorry for opening a issue for this, if its not appropriate)

Thanks again and congratulations for this project.

**Comment by NickCarneiro** [comment]
Thanks. It's not too hard, just tedious.

Rough outline:

1) Add a new file in `generators/` called swift.js. You can work off of `generators/php.js` as an example.
2) Include that file in index.js, following the existing pattern.
3) Add some tests to the end of test.js. You'll also need to include some new test fixtures.

I've never written swift, but I'll try to get the development environment running.
