### ISSUE TITLE
error parsing curl command for Twilio

### ISSUE THREAD

**Issue by FrancisVila** [NickCarneiro/curlconverter#210]
Here's the command, it sends an SMS via Twilio (verified, it does work):

curl -X POST "https://staging.cloud-elements.com/elements/api-v2/messages" -H  "accept: application/json" -H  "Authorization: User uuuuuuuuuuu=, Organization oooooooooooooooo, Element eeeeeeeeeeeeee=" -H  "Content-Type: application/json" -d "{  \"Body\": \"hi there\",  \"From\": \"+123456789\",  \"To\": \"+987654321\"}"

**Comment by einstein95** [comment]
This is due to the `-d` argument being improperly formatted. The data contains quotation marks, which are being used to wrap the data in.
Converting ```curl -X POST "https://staging.cloud-elements.com/elements/api-v2/messages" -H "accept: application/json" -H "Authorization: User uuuuuuuuuuu=, Organization oooooooooooooooo, Element eeeeeeeeeeeeee=" -H "Content-Type: application/json" -d '{ "Body": "hi there", "From": "+123456789", "To": "+987654321"}'``` works fine (note the use of apostrophes instead of quotation marks)

**Comment by FrancisVila** [comment]
Thanks @einstein95 ! It looks pretty obvious once it's pointed out...
