### ISSUE TITLE
Fails to parse this curl command

### ISSUE THREAD

**Issue by NoahCardoza** [NickCarneiro/curlconverter#211]
```curl - H 'Host: api.3stripes.net' - H 'Cookie: akacd_api_3stripes=3764610359~rv=82~id=613340aff0e8a44143ae8943e1c5bb82' - H 'accept: application/hal+json' - H 'x-device-info: app/adidas; os/iOS; os-version/13.3; app-version/3.25; buildnumber/2020.4.9.17.7; type/iPhone10,1; fingerprint/HFEWLKEF-5003-467C-AE1E-C285853097A3' - H 'x-market: US' - H 'x-signature: FJEWLJFWEIUHFOIEUWHFOUIEWH' - H 'x-devicetoken: FEHWIJHF-69C5-48DB-9382-63EFA6697CC8' - H 'accept-language: en-US' - H 'x-api-key: feuwoifyyewfoiuyewoi' - H 'user-agent: adidas/2020.4.9.17.7 CFNetwork/1121.2.2 Darwin/19.2.0' 'https://api.3stripes.net/gw-api/v2/user/lookup?id=email@gmail.com'```

**Comment by NoahCardoza** [comment]
This is my bad. My editor put spaces around the dashes.

**Comment by alinbasuljevic** [comment]
Are you on discord? I tried adding you and nothing came up. Trying to do something similar to you it seems (just by looking at this code).

**Comment by NickCarneiro** [comment]
@alinbasuljevic Noah has spaces between the dash and the `H`. If you remove those it should parse correctly.
