### ISSUE TITLE
Add generator for Java

### ISSUE THREAD

**Issue by NickCarneiro** [NickCarneiro/curlconverter#22]
Java is super popular and super verbose, making it a good candidate for curlconverter.

We need to find out if there is some modern library for sending http requests. Please advise.

I've used the Apache HttpClient before, but this looks interesting: http://unirest.io/java.html
There's no reason we couldn't have two generators.

**Comment by D063520** [comment]
Why was this enhancement closed?

**Comment by NickCarneiro** [comment]
It didn't look like there was much interest back then. I'll reopen it so maybe this will get some more eyeballs on it and someone will pick it up.

**Comment by Lonor** [comment]
It's 2020 now.

**Comment by NickCarneiro** [comment]
@Lonor Are you saying you want a Java generator?

**Comment by Lonor** [comment]
yep

**Comment by rainydew** [comment]
> @Lonor Are you saying you want a Java generator?

and me too

**Comment by jgroom33** [comment]
someone that regularly codes java needs to write this.  This curlconverter library is very simple.  Java is not.

**Comment by verhovsky** [comment]
Java support was added in #255
