### ISSUE TITLE
Does not work in MS Edge - JS error Expected '('  

### ISSUE THREAD

**Issue by szabgab** [NickCarneiro/curlconverter#223]
I type in a sample code and nothing happens even with an example as simple as this:
```
curl http://example.com
```

At first I thought the "convert" button was missing, but then I looked at the JS console that shows this error:

```
SCRIPT1005: SCRIPT1005: Expected '('  main.min.js (1854,13)
```

On the same Windows machine using Chrome the site works perfectly.

**Comment by romadrutskii** [comment]
@szabgab, please, update your Microsoft Edge [here](https://www.microsoft.com/en-us/edge). The latest version works fine.
