### ISSUE TITLE
Curl command unable to parse

### ISSUE THREAD

**Issue by sudipta2311** [NickCarneiro/curlconverter#225]
curl 'https://mydomain.com/api/test' \
  -H 'authority: mydomain.com' \
  -H 'accept: application/json' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36' \
  -H 'x-app-name: test' \
  -H 'x-request-id: ckc1epzu400093h5qqxpzt5rm' \
  -H 'content-type: application/json' \
  -H 'origin: https://mydomain.com' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://mydomain.com/' \
  -H 'accept-language: en-IN,en-US;q=0.9,en-GB;q=0.8,en;q=0.7' \
  -H 'cookie: _ga=GA1.2.8043209.1592284850; _gid=GA1.2.904405262.1593378624; _gat=1; erp.token=362137be80d65b25017edbe3d03a83f116627e45747d593dba04735a100766759356c6fbe682c9020699e03226bbccbb; session=Yhu-Z9qv9qw7xU25Mz8Y6Q.thh5DfOuv4_yggRKa7VSrTi8GY294d935le3PWFOgpSGgzzUIHnB5qV-6WjcY9PmwQwOppAK6aqnicJP563NXU6Ro77rul0cUalpT7miGgxoAsgvD3Nl07pxLKQD8-_F.1593489849223.2592000000.BgVwdpwb4T4eF0Bp1rzzMklXsQBjEVCe0maBH2tDj7c' \
  --data-binary '{"name":"","graphType":"MATRIX","widgetTemplateId":"5e8c55a7c013045c8cf8e49f","filters":[{"name":"PRODUCT_FILTER_BUCKET","displayName":"PRODUCT_FILTER_BUCKET","values":[{"name":"MAPPED_PRODUCTS","displayName":"MAPPED_PRODUCTS"}]},{"name":"CATEGORY","displayName":"Category","values":[{"name":"Men-Tshirts","displayName":"Men-Tshirts"}]},{"name":"MARKETPLACE","displayName":"Marketplace","values":[{"name":"test","displayName":"Test"}]},{"name":"BRAND","displayName":"Brand","values":[]},{"name":"DISCOUNT_BUCKET","displayName":"Discount Range","values":[{"name":"10.0-20.0","displayName":"10 - 20%"},{"name":"20.0-30.0","displayName":"20 - 30%"},{"name":"30.0-40.0","displayName":"30 - 40%"},{"name":"40.0-50.0","displayName":"40 - 50%"},{"name":"50.0-60.0","displayName":"50 - 60%"},{"name":"60.0-70.0","displayName":"60 - 70%"},{"name":"70.0-80.0","displayName":"70 - 80%"},{"name":"80.0-90.0","displayName":"80% +"},{"name":"0.0-10.0","displayName":"0 - 10%"}]},{"name":"AVAILABILITY_BUCKET","displayName":"Availability","values":[{"name":"IN_STOCK","displayName":"In Stock"},{"name":"SIZE_BREAK","displayName":"Size Break"},{"name":"OUT_OF_STOCK","displayName":"Out of Stock"}]}],"axisAttributeKey":null,"widgetMetricsLimit":null,"widgetMetric":[{"aggregateTypes":["COUNT","PERCENTAGE"],"metric":"PRODUCT"},{"aggregateTypes":["MIN","MAX","MEDIAN"],"metric":"SELLING_PRICE"},{"aggregateTypes":["MIN","MAX","MEDIAN"],"metric":"DISCOUNT"}],"dateFilter":{"startDate":"2020-03-30T04:04:23.217+0000","endDate":"2020-06-30T04:04:23.217+0000","useCustomRange":false,"quickRange":"LAST_3_MONTHS"}}' \
  --compressed

**Comment by jgroom33** [comment]
Please narrow this down to the offending entity.
