### ISSUE TITLE
Error parsing curl command.

### ISSUE THREAD

**Issue by NarottamSaini** [NickCarneiro/curlconverter#232]
curl  -u ccds_client:ccds_client -X POST http://cognita-dev1-vm01-core.eastus.cloudapp.azure.com:8002/ccds/artifact -H accept: application/json -H Content-Type: application/json -djsonValue 
{ "artifactTypeCode": "DI",  "created": "2020-05-14T11:57:55.027Z",  "description": "acumos-nexus01.eastus.cloudapp.azure.com:18001/Iris_sklearn_proba_fbdb866f-c647-467d-a766-37060501e114:1.0.54", "modified": "2020-05-14T11:57:55.029Z",  "name": "Iris_sklearn_proba",  "size": -1,  
"uri": "acumos-nexus01.eastus.cloudapp.azure.com:18001/Iris_sklearn_proba_fbdb866f-c647-467d-a766-37060501e114:1.0.54",  "userId": "3ac5c05a-394a-4e06-af7a-2b8fd40e033e",  "version": "1.0.54"}

**Comment by cf512** [comment]
It can't parse due to: 1) -djsonValue, 2) the json object needs to be wrapped in quotes, and 3) the -H values needing quotes too.

Try:

```
curl -u ccds_client:ccds_client -X POST http://cognita-dev1-vm01-core.eastus.cloudapp.azure.com:8002/ccds/artifact -H "accept: application/json" -H "Content-Type: application/json" -d "{"artifactTypeCode": "DI", "created": "2020-05-14T11:57:55.027Z", "description": "acumos-nexus01.eastus.cloudapp.azure.com:18001/Iris_sklearn_proba_fbdb866f-c647-467d-a766-37060501e114:1.0.54", "modified": "2020-05-14T11:57:55.029Z", "name": "Iris_sklearn_proba", "size": -1,
"uri": "acumos-nexus01.eastus.cloudapp.azure.com:18001/Iris_sklearn_proba_fbdb866f-c647-467d-a766-37060501e114:1.0.54", "userId": "3ac5c05a-394a-4e06-af7a-2b8fd40e033e", "version": "1.0.54"}"
```

**Comment by NarottamSaini** [comment]
Thanks cf512 for the resolution.
