### ISSUE TITLE
Ansible generator can't generate the simplest CURL (no https://curl.trillworks.com/templates//ansible.j2)

### ISSUE THREAD

**Issue by epsimatic** [NickCarneiro/curlconverter#238]
First of all, it's the only generator wanting my request to start with `curl` characters (no whitespace or comments)

## Big curl command:

```bash
curl -X "POST" "http://192.168.0.1/goform/goform_set_cmd_process" -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' --data-urlencode "goformId=CONNECT_NETWORK"
```

_(Exported by https://github.com/LuckyMarmot/Paw-cURLCodeGenerator)_

**Error parsing curl command.**

## Minimal curl command:

```bash
curl http://192.168.0.1/goform/goform_set_cmd_process
```

**Error parsing curl command.**

Most likely the issue is: https://curl.trillworks.com/templates//ansible.j2?s=1596906581266 is not found.

**Comment by NickCarneiro** [comment]
Looks like I broke ansible in the web ui when deploying the new template-based generator.

As a workaround, use the npm package to run curlconverter locally. There's an example in the readme. I'll fix the web ui later today.

**Comment by epsimatic** [comment]
No worries and no workaround needed (for me). Just reporting the issue since your page suggested to do it.

Thanks for the neat service btw

**Comment by NickCarneiro** [comment]
This is fixed here: https://github.com/NickCarneiro/curlconverter/commit/01f44a22c6a3212a3d617b1504d082020fd9e5c9

Thanks for the bug report!
