### ISSUE TITLE
-u command does not work

### ISSUE THREAD

**Issue by varunvt126** [NickCarneiro/curlconverter#24]

**Comment by NickCarneiro** [comment]
Can you provide a few example commands?

**Comment by xiaolin** [comment]
curl "https://api.test.com/" -u ":some_password"

**Comment by imravichaudhary** [comment]
curl -X PUT http://localhost:5984/test/_security -u "admin:123" -d '{"admins":{"names":[], "roles":[]}, "readers":{"names":["joe"],"roles":[]}}'

**Comment by NickCarneiro** [comment]
I've added basic auth support for python, node, and php in 0.0.27. The code is live.

Thank you for providing examples, @xiaolin and @imravichaudhary.
