### ISSUE TITLE
Change Node.js request module

### ISSUE THREAD

**Issue by weslenng** [NickCarneiro/curlconverter#241]
With `request` module [being deprecated](https://github.com/request/request/issues/3142), it's a good time to change the request module in the Node.js generated code
We have some good alternatives like [`axios`](https://github.com/axios/axios), [`got`](https://github.com/sindresorhus/got) or [`node-fetch`](https://github.com/node-fetch/node-fetch)

I think the last one is the most suitable

**Comment by NickCarneiro** [comment]
fetch seems like a good way to go. We can keep requests around as a legacy option for a bit and rename it in the dropdown.

**Comment by weslenng** [comment]
> Fetch seems like a good way to go. We can keep `request` around as a legacy option for a bit and rename it in the dropdown

What do you think of put the core logic of [`generators/browser.js`](https://github.com/NickCarneiro/curlconverter/blob/e9b31423566df318a7ecf4d55b39a5231b23f777/generators/browser.js) into a `js-fetch` file to use in both `browser` and `node-fetch` generators?

**Comment by NickCarneiro** [comment]
It's a good idea. We will still have to have to pass in browser/nonbrowser boolean for the `const fetch = require('node-fetch');` line, but everything else should hopefully be the same.
