### ISSUE TITLE
Can't convert to python requests

### ISSUE THREAD

**Issue by mcroni** [NickCarneiro/curlconverter#251]
Currently trying to use messagebird api for app but converting the curl command into python game some wrong output.
`curl -X "POST" "https://conversations.messagebird.com/v1/send" \\
-H "Authorization: AccessKey 22323232323232323" \\
-H "Content-Type: application/json" \\
--data '{ "to":"+31XXXXXXXXX", "from":"WHATSAPP-CHANNEL-ID", "type":"text", "content":{ "text":"Hello!" }, "reportUrl":"https://example.com/reports" }`

its python equivalent displayed is
`import requests
response = requests.post('https://conversations.messagebird.com/v1/send')`

**Comment by NickCarneiro** [comment]
I'm not able to reproduce this on curl.trillworks.com.

When pasting your input I see this on chrome.

```
import requests

headers = {
    'Authorization': 'AccessKey 22323232323232323',
    'Content-Type': 'application/json',
}

data = '{ "to":"+31XXXXXXXXX", "from":"WHATSAPP-CHANNEL-ID", "type":"text", "content":{ "text":"Hello!" }, "reportUrl":"https://example.com/reports" }'

response = requests.post('https://conversations.messagebird.com/v1/send', headers=headers, data=data)

```

**Comment by verhovsky** [comment]
In your input you are missing the `'` at the end.

```
example.com/reports" }    <-- should end with '
```

and also you have double backslashes for some reason, which would not be a valid bash curl command. Replacing them with single backslashes and adding the missing "'"

```sh
curl -X "POST" "https://conversations.messagebird.com/v1/send" \
    -H "Authorization: AccessKey 22323232323232323" \
    -H "Content-Type: application/json" \
    --data '{ "to":"+31XXXXXXXXX", "from":"WHATSAPP-CHANNEL-ID", "type":"text", "content":{ "text":"Hello!" }, "reportUrl":"https://example.com/reports" }'
```

it seems to work so I am closing this issue.
