### ISSUE TITLE
Bad conversion

### ISSUE THREAD

**Issue by fuad47** [NickCarneiro/curlconverter#258]
I tried to convert this Curl but `data` variable converted with mistakes as a result my request didnt work.
`curl "https://query2.finance.yahoo.com/v1/finance/screener?crumb=Tu9bE6gdyG2&lang=en-CA&region=CA&formatted=true&corsDomain=ca.finance.yahoo.com" ^
  -H "authority: query2.finance.yahoo.com" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36" ^
  -H "content-type: application/json" ^
  -H "accept: */*" ^
  -H "origin: https://ca.finance.yahoo.com" ^
  -H "sec-fetch-site: same-site" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-dest: empty" ^
  -H "referer: https://ca.finance.yahoo.com/gainers" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "cookie: APID=UPaf0bcdea-43b5-11eb-abda-02d09716fa14; B=2bfurvhfu12jc&b=3&s=9p; EuConsent=CPDqUdIPDqUdIAOACBENBACoAP_AAH_AACiQHCNd_X_fb39j-_59__t0eY1f9_7_v20zjgeds-8Nyd_X_L8X_2M7vB36pr4KuR4ku3bBAQFtHOncTQmx6IlVqTPsak2Mr7NKJ7PEinsbe2dYGHtfn9VT-ZKZr97s___7________79______3_vt_9__wOCAJMNS-AizEscCSaNKoUQIQriQ6AEAFFCMLRNYQErgp2VwEfoIGACA1ARgRAgxBRiyCAAAAAJKIgBADwQCIAiAQAAgBUgIQAEaAILACQMAgAFANCwAigCECQgyOCo5TAgIkWignkrAEou9jDCEMooAaAAA; A1=d=AQABBGyK4F8CEPf4QoqY-XpAwtTV8PzbvyUFEgABAgEAX2AqYQ7lbmUB9iMAAAcIbIrgX_zbvyU&S=AQAAAu3mgPdNNOi1SqS_6AwjZ08; A1S=d=AQABBGyK4F8CEPf4QoqY-XpAwtTV8PzbvyUFEgABAgEAX2AqYQ7lbmUB9iMAAAcIbIrgX_zbvyU&S=AQAAAu3mgPdNNOi1SqS_6AwjZ08&j=WORLD; GUC=AQABAgFgXwBhKkIh6wTL; cmp=v=18&t=1616932563&j=1; APIDTS=1616932767; PRF=t^%^3DPOW.TO^%^252BHKDCNY^%^253DX^%^252BEURUSD^%^253DX^%^252BSGD^%^253DX^%^252BBTC-GBP^%^252BBTC-USD^%^252BZNN-USD^%^252BMASS-USD^%^252BSUB-USD^%^252B^%^255EGSPC^%^252B000001.SS^%^252B^%^255EMXX^%^252BJPY^%^253DX^%^252BAPI^%^252BEURGBP^%^253DX; A3=d=AQABBGyK4F8CEPf4QoqY-XpAwtTV8PzbvyUFEgABAgEAX2AqYQ7lbmUB9uMAAAcIbIrgX_zbvyU&S=AQAAAqgehujnx-zJB-iJ3QMdvo8" ^
  --data-raw "^{^\^"offset^\^":0,^\^"size^\^":25,^\^"sortField^\^":^\^"percentchange^\^",^\^"sortType^\^":^\^"desc^\^",^\^"quoteType^\^":^\^"equity^\^",^\^"query^\^":^{^\^"operator^\^":^\^"and^\^",^\^"operands^\^":^[^{^\^"operator^\^":^\^"gt^\^",^\^"operands^\^":^[^\^"percentchange^\^",2.5^]^},^{^\^"operator^\^":^\^"or^\^",^\^"operands^\^":^[^{^\^"operator^\^":^\^"EQ^\^",^\^"operands^\^":^[^\^"region^\^",^\^"ca^\^"^]^},^{^\^"operator^\^":^\^"EQ^\^",^\^"operands^\^":^[^\^"region^\^",^\^"ar^\^"^]^}^]^},^{^\^"operator^\^":^\^"gt^\^",^\^"operands^\^":^[^\^"dayvolume^\^",100000^]^}^]^},^\^"userId^\^":^\^"^\^",^\^"userIdType^\^":^\^"guid^\^"^}" ^
  --compressed` 

Correct version should be like: 
`data = {"offset":0,"size":25,"sortField":"percentchange","sortType":"desc","quoteType":"equity","query":{"operator":"and","operands":[{"operator":"gt","operands":["percentchange",2.5]},{"operator":"or","operands":[{"operator":"EQ","operands":["region","ca"]},{"operator":"EQ","operands":["region","ar"]}]},{"operator":"gt","operands":["dayvolume",100000]}]},"userId":"","userIdType":"guid"}`

**Comment by verhovsky** [comment]
Seeing the `^` characters in your input command, I think this is the same issue as #143, i.e. you clicked "`Copy as cURL (cmd)`" instead of clicking on the regular "Copy as cURL". `curlconverter` doesn't support cmd curl commands.
