### ISSUE TITLE
Holy shit.

### ISSUE THREAD

**Issue by Kladdkaka** [NickCarneiro/curlconverter#27]
I'm sorry about using issues for this,
But holy shit, thank you so much for creating this.
I was really frustrated with making a post request node.js. But I couldn't get it to work, and I was about to give up completely, but then somehow I stumbled upon your tool, and decided "why not test this?". So I did, and I posted it into my code, and it just magically worked.
Thank you so much.

If I wasn't a broke teenager then I would have bought you a pizza or anything. But I hope this thank you is enough =)

/Erik

**Comment by NickCarneiro** [comment]
hack the planet
