### ISSUE TITLE
Cannot install on Apple Silicon

### ISSUE THREAD

**Issue by GarrettRector** [NickCarneiro/curlconverter#271]
I tried installing on my M1 MacBook, but it seems that the chromium binary's aren't available. So I installed chromium with brew, as some people online have said that this fixed the issue, but it still cannot find them. Anybody able to solve this issue?

**Comment by cf512** [comment]
Unclear if this issue is specific to curlconverter -- is it? Please send replication steps and/or excerpts from your terminal.

**Comment by GarrettRector** [comment]
Well its a puppeteer error with chromium not supporting arm as of right now. I tried the solutions posted on that repo and still no luck. I'm just doing it on my pc now
