### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by lueans** [NickCarneiro/curlconverter#279]
****@ubuntu:~$ npm install  curlconverter
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/NickCarneiro/yargs-ansi.git
npm ERR! 
npm ERR! ssh_exchange_identification: read: Connection reset by peer
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lueans/.npm/_logs/2021-09-15T14_02_22_912Z-debug.log

**Comment by verhovsky** [comment]
https://www.google.com/search?q=npm+cant+install+ssh+git+Connection+reset+by+peer

https://stackoverflow.com/questions/43326527/npm-and-bower-updates-fail-majority-of-the-time-depending-on-the-network
