### ISSUE TITLE
Add import statement to python code

### ISSUE THREAD

**Issue by Hammer2900** [NickCarneiro/curlconverter#28]
when convert import to python code will be good if import request library is exist (import request). 
and add object output like 

r = requests.post('http://127.0.0.1:8000/api/membership_type/', headers=headers, data=data)
print r.text <------

**Comment by NickCarneiro** [comment]
We import libraries in node.js and php code. We should import requests in the php code to be consistent.

However, I am going to hold off on the print statement for now. I need to think about it more.

**Comment by Hammer2900** [comment]
Thank you !!! )) for import requests man !
