### ISSUE TITLE
function 

### ISSUE THREAD

**Issue by iojkn** [NickCarneiro/curlconverter#293]
hi! Is it possible to get some api for this?

**Comment by verhovsky** [comment]
What is your intended use-case that you wouldn't prefer to install curlconverter yourself? It comes with a command line tool, you just do

```sh
$ npm install -g curlconverter
[...]
$ echo curl example.com | curlconverter
import requests

response = requests.get('http://example.com')
```

and you'll get results faster and more reliably from an API.
