### ISSUE TITLE
--data-binary fails to read file into string

### ISSUE THREAD

**Issue by mit2nil** [NickCarneiro/curlconverter#32]
Hi, 

I used following CURL command, 

`
curl -i -X POST \
--data-binary @./sample.sparql \
-H "Content-type: application/sparql-query" \
-H "Accept: application/sparql-results+json" \
http://lodstories.isi.edu:3030/american-art/query
`

which resulted in below code,

`
import requests

headers = {
    'Content-type': 'application/sparql-query',
    'Accept': 'application/sparql-results+json',
}

data = open('./sample.sparql')
requests.post('http://lodstories.isi.edu:3030/american-art/query', headers=headers, data=data)
`

However, this fails to return any results. I had to replace line `data = open('./sample.sparql')` with `data = open('./sample.sparql', 'rb').read()` to get it working.

**Comment by NickCarneiro** [comment]
Are you using python on windows?

**Comment by mit2nil** [comment]
Yes

**Comment by NickCarneiro** [comment]
That explains the issue. I've deployed a fix.
