### ISSUE TITLE
Add python support for multipart forms

### ISSUE THREAD

**Issue by Cian-Chambliss** [NickCarneiro/curlconverter#33]
Example script, produces code that has no body - note that -F option is used instead of  --data to send multiple parts:

var curlconverter = require('curlconverter');
curlIn = 'curl https://upload.box.com/api/2.0/files/content -H "Authorization: Bearer ACCESS_TOKEN" -X POST -F attributes=\'{"name":"tigers.jpeg", "parent":{"id":"11446498"}}\' -F file=@myfile.jpg';
var script = curlconverter.toPython(curlIn);
console.log(script);

**Comment by NickCarneiro** [comment]
I've deployed basic support for multipart forms in 1.0.4. It is kind of brittle but will work for now.
