### ISSUE TITLE
It is removing important info during conversion

### ISSUE THREAD

**Issue by willbishop** [NickCarneiro/curlconverter#35]
I cannot post the cURL request here, as it accesses sensitive accounts.

If the dev is still maintaining this, please reply so I can contact you

**Comment by NickCarneiro** [comment]
Can you create an example with similar content?

**Comment by 123icebuggy** [comment]
i can't unfortunately

**Comment by NickCarneiro** [comment]
well, feel free to send me an email.

**Comment by 123icebuggy** [comment]
Done

**Comment by NickCarneiro** [comment]
Parsing of --data-binary strings was busted. Give it another shot.
