### ISSUE TITLE
copy curl request from Charles, url undefine

### ISSUE THREAD

**Issue by rpplusplus** [NickCarneiro/curlconverter#4]
I use [Charles](http://www.charlesproxy.com/) get curl Request, get that:

```
curl -H "Host: api.ipify.org" -H "Accept: */*" -H "User-Agent: GiftTalk/2.7.2 (iPhone; iOS 9.0.2; Scale/3.00)" -H "Accept-Language: en-CN;q=1, zh-Hans-CN;q=0.9" --compressed http://api.ipify.org/?format=json&
```

the curl write in terminal works fine, but  I wrote into http://curl.trillworks.com/, got

```
headers = {
    'Host': 'api.ipify.org',
    'Accept': '*/*',
    'User-Agent': 'GiftTalk/2.7.2 (iPhone; iOS 9.0.2; Scale/3.00)',
    'Accept-Language': 'en-CN;q=1, zh-Hans-CN;q=0.9',
}

requests.get('undefined', headers=headers)
```

**Comment by NickCarneiro** [comment]
This package only support curl syntax generated by Chrome. If you send a
pull request for supporting more general curl syntax I will accept it.

**Comment by joshuataylor** [comment]
If you want to use Charles and this tool, just move the URL right after ```curl``` and put the URL in ''.
