### ISSUE TITLE
convert below curl command to requests

### ISSUE THREAD

**Issue by kishore0709** [NickCarneiro/curlconverter#46]
Hi,

How to convert below curl command to requests in python.

'curl -d "cmd_typ=22&cmd_mod=2&host=somehostname&service=someservice&btnSubmit=Commit" username:password@nagiosserver.com/nagios/cgi-bin/cmd.cgi

Thanks

**Comment by einstein95** [comment]
https://curl.trillworks.com/ works fine with the command you gave

**Comment by kishore0709** [comment]
Thanks for your comment. I tried but its giving "unable to parse" error.

**Comment by einstein95** [comment]
Remove the `'` from before `curl`

**Comment by kishore0709** [comment]
Awesome it worked for me. Thank you very much.

**Comment by NickCarneiro** [comment]
I've updated the error message to warn if the input does not start with "curl". Thanks, @einstein95
