### ISSUE TITLE
header fields are ignored

### ISSUE THREAD

**Issue by ErKatz** [NickCarneiro/curlconverter#47]
Hi.
Consider the following Curl Command:

curl -X GET --header 'Accept: application/json' --header 'user-token: 75d7ce4350c7d6239347bf23d3a3e668' 'http://localhost:8080/api/retail/books/list'

It gets converted to:

`import requests

requests.get('http://localhost:8080/api/retail/books/list')
`

the "user-token" is ignored.
Instead it should be converted to:

`import requests

requests.get('http://localhost:8080/api/retail/books/list',headers={'user-token': '75d7ce4350c7d6239347bf23d3a3e668')
`

**Comment by einstein95** [comment]
Replacing `--header` with `-H` works
