### ISSUE TITLE
Short form of insecure (-k) request not working

### ISSUE THREAD

**Issue by aderon2** [NickCarneiro/curlconverter#50]
The syntax in the following curl command is correct, but the converter won't convert it to python requests.

curl -k 'https://www.site.com'

Great program btw!  I'm pretty familiar with curl, but am just learning requests and your converter has helped me learn a lot.

**Comment by NickCarneiro** [comment]
I'll get this fixed soon.

output will look like this:


```
import requests

requests.get('https://example.com/', verify=False)
```
