### ISSUE TITLE
Parse -XPOST and -XGET commands

### ISSUE THREAD

**Issue by glinhofe** [NickCarneiro/curlconverter#51]
Following curl call works for me with curl, but your parser throws an error when it tries to parse it:
`curl -XPOST 'http://us.jooble.org/api/xxxxxxxxxxxxxxxx' --data '{"keywords":"php","page":1,"searchMode":1}'`

**Comment by NickCarneiro** [comment]
Interesting case. Add another `-` in front of XPOST and it should work. I'll investigate.

**Comment by NickCarneiro** [comment]
fixed in 1.7.0
