### ISSUE TITLE
Do not include filename when using multipart/form-data field that is not a file

### ISSUE THREAD

**Issue by viralsword** [NickCarneiro/curlconverter#53]
Noticed curlconverter is converting all cURL -F as 'files'. But not all -F are files, some are actual form data, also Python 'requests' adds 'filename' field if you send as 'files'.  

Only curl form data with '@' can be uploaded using 'files', remaining everything should go as 'data'

**Comment by NickCarneiro** [comment]
It looks like the files argument with a dict of tuples with `None` as the first entry is still the preferred way for sending non-file multipart/form-data through requests.
```

files = {
    'username': (None, 'davidwalsh'),
    'password': (None, 'something')
}

requests.post('https://httpbin.org/post', files=files)
```
This is pretty ugly, but it gets rid of the filename field and should help compatibility.
