### ISSUE TITLE
--user-agent ignored in python conversion

### ISSUE THREAD

**Issue by gopalprasad780** [NickCarneiro/curlconverter#58]
Here is my curl command.. (please note I have replaced the number with xxxxxxxxx)
curl  --trace-ascii log2.txt --user-agent "Mozilla Android6.1" -i --header "x-msisdn:XXXXXXXXXXXXX" -L "http://205.147.98.6/vc/moviesmagic?p=5&pub=testmovie&tkn=817263812"

**Comment by NickCarneiro** [comment]
It looks like this command parses without errors, but `--user-agent` is being ignore. That's not good.

I don't feel like adding support for `--trace-ascii`, but the user agent problem is a bug and will be fixed.
