### ISSUE TITLE
Convert curl syntax to Python, Node.js, PHP

### ISSUE THREAD

**Issue by Artus91** [NickCarneiro/curlconverter#60]
I used link https://curl.trillworks.com/#python to convert curl command to python requests syntax. But it show me error "Error parsing curl command".

Syntax of curl command
`curl https://android.googleapis.com/gcm/send -H 'Content-Type: Application/json' -H  'Authorization: key=sdfwer24s:345sdfwer25dfg9dVtpddf345dfg' -d '{"registration_ids":["sdfg34fsg3s:345fw4tsfgsdftg3w5esrert-345"], "data":{"data":"sdf23sdf dsf"}}'`

There are problems  in AUTH_KEY and registration Ids, because they contains symbols **:**.

**Comment by NickCarneiro** [comment]
I am having trouble reproducing this issue.
![google api request](https://user-images.githubusercontent.com/700209/30776117-aadb0428-a055-11e7-9991-4e8e25255c0e.png)

Any more information you can give me?
