### ISSUE TITLE
Add python support for OPTIONS request method

### ISSUE THREAD

**Issue by henfri** [NickCarneiro/curlconverter#62]
Hello,

I am trying to convert his:

`curl "https://layla.amazon.de/api/tunein/queue-and-play?deviceSerialNumber=xxx^&deviceType=xxx^&guideId=s56876^&contentType=station^&callSign=^&mediaOwnerCustomerId=xxx" -X OPTIONS -H "Pragma: no-cache" -H "Access-Control-Request-Method: POST" -H "Origin: https://alexa.amazon.de" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" -H "Accept: */*" -H "Cache-Control: no-cache" -H "Referer: https://alexa.amazon.de/spa/index.html" -H "Connection: keep-alive" -H "DNT: 1" -H "Access-Control-Request-Headers: content-type,csrf" --compressed`

I think, this should be a post request. Nevertheless, it is always converted to a get request.
How can I enforce a post?

Greetings,
Hendrik

**Comment by NickCarneiro** [comment]
This curl command sends an OPTIONS request.

The output (GET) is wrong. It looks like requests supports options so it shouldn't be too hard to add support.

For your case, just do something like `requests.options(r.url)`

**Comment by NickCarneiro** [comment]
fixed in 1.11.10
