### ISSUE TITLE
binary data argument not reflected in requests output

### ISSUE THREAD

**Issue by mikeyford** [NickCarneiro/curlconverter#67]
Hey there,

Really useful tool! Thank you very much. I got thrown for a bit of a loop when uploading a file to an AWS S3 (nice work on parsing the auth url BTW). The curl had the argument `--data-binary` however the requests output still suggested using `requests.put(url, data=data)`. The solution to this seems to be 

`with open(file, 'rb') as data:`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`requests.put(url, data=data)`

(https://stackoverflow.com/questions/31341808/how-to-do-put-on-amazon-s3-using-python-requests)

Maybe it's obvious that the data needs to be read as binary to more experienced users, but from my perspective: maybe it's worth a comment in the output or using different parsing to draw attention to that?

Would be happy to try and implement that myself if you agree.

**Comment by NickCarneiro** [comment]
Can you post the original curl command?
