### ISSUE TITLE
curl -L does not work for Python requests

### ISSUE THREAD

**Issue by shichao-an** [NickCarneiro/curlconverter#7]
```
curl -L http://www.google.com
```

converts to

```
requests.get('undefined')
```

**Comment by NickCarneiro** [comment]
Arbitrary curl syntax is not supported right now. This only works with the curl requests that Chrome spits out.

If you want to special case this in a pull request I'll accept it.

**Comment by NickCarneiro** [comment]
Sort of fixed in 0.0.21. -L does not break url parsing, but it does not implement redirect following behavior. If there's demand, that can be another issue.
