### ISSUE TITLE
Please convert to python

### ISSUE THREAD

**Issue by ghwgs6** [NickCarneiro/curlconverter#75]
curl 'https://810be097-b1e3-4f9c-b0bb-0d18052080bf.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token' -H 'Pragma: no-cache' -H 'content-type: application/x-www-form-urlencoded' -H 'Cache-Control: no-cache' -H 'authorization: Basic bW9ybmVkZXZpbGxpZXJzX2FwcDoxMDgxME1vcm5lQCM=' --data 'client_id=mornedevilliers_app&grant_type=client_credentials'

**Comment by nicktimko** [comment]
This appears to work just fine on the live site. Is it incorrect? What do you expect?

**Comment by ghwgs6** [comment]
Yes was my fault thx
