### ISSUE TITLE
Issue in converting 

### ISSUE THREAD

**Issue by Prashast07** [NickCarneiro/curlconverter#81]
I am trying to convert following curl command to python
curl -X GET -H “Content-Type: application/json” -H “Accept: application/json” -H “icSessionId”:“XXXXXXXXXX” https://app3.informaticacloud.com/saas/api/v2/agent

The output i am getting is 
import requests

headers = {
    '\u201CContent-Type': '',
    '\u201CAccept': '',
    '\u201CicSessionId\u201D': '\u201Cxxxxxxxxxxxxxxx\u201D',
}

response = requests.get('http://application/json”', headers=headers)

In the output i am no where getting the URL

**Comment by NickCarneiro** [comment]
I have no plans to support left / right double quotes.

It looks like you're using Unicode Character 'LEFT DOUBLE QUOTATION MARK' (U+201C)

Please stick with ascii quotes. U+0022

https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html
