### ISSUE TITLE
Getting response 500, while curl works fine.

### ISSUE THREAD

**Issue by sv3nster** [NickCarneiro/curlconverter#82]
Just as the title says. Here's the curl command (trimmed cookie a tad for brevity):

`curl 'http://10.212.143.111/Ion/default.aspx/GetRTxmlData' -H 'Cookie: ASP.NET_SessionId=ee4a3gjs2dgyzgy3y3putp50; .APPLICATIONFRAMEWORK=D684EB482F28D2A34E3D38261250545C25D77913B62F7B5D275E9708FF97A0AED07EB8DDEF74798D85F51D588D1CB5D534C42620639C879A24514BEE36C87201F4D0835822EE7F' -H 'Origin: http://10.212.143.111' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36' -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://10.212.143.111/Ion/default.aspx' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data-binary $'{\'subsKey\':\'x-pml:/diagrams/ud/network.dgm@\'}' --compressed
`

Curl Response (trimmed):

`{"d":"\u003cDiagramInput savedAt=\"2018-02-10 05:51:46\" xmlns=\"http://rddl.xmlinside.net/PowerMeasurement/data/webreach/realtime/1/\"\u003e\r\n  \u003cItems nodeName=...`

Curlconverter Response:
`<Response [500]>`

**Comment by romadrutskii** [comment]
> 
> 
> Just as the title says. Here's the curl command (trimmed cookie a tad for brevity):
> 
> `curl 'http://10.212.143.111/Ion/default.aspx/GetRTxmlData' -H 'Cookie: ASP.NET_SessionId=ee4a3gjs2dgyzgy3y3putp50; .APPLICATIONFRAMEWORK=D684EB482F28D2A34E3D38261250545C25D77913B62F7B5D275E9708FF97A0AED07EB8DDEF74798D85F51D588D1CB5D534C42620639C879A24514BEE36C87201F4D0835822EE7F' -H 'Origin: http://10.212.143.111' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36' -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://10.212.143.111/Ion/default.aspx' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data-binary $'{\'subsKey\':\'x-pml:/diagrams/ud/network.dgm@\'}' --compressed `
> 
> Curl Response (trimmed):
> 
> `{"d":"\u003cDiagramInput savedAt=\"2018-02-10 05:51:46\" xmlns=\"http://rddl.xmlinside.net/PowerMeasurement/data/webreach/realtime/1/\"\u003e\r\n \u003cItems nodeName=...`
> 
> Curlconverter Response:
> `<Response [500]>`

Works fine for me. 
`
{"args":{},"data":"${\'subsKey\':\'x-pml:/diagrams/ud/network.dgm@\'}","files":{},"form":{},"headers":{"x-forwarded-proto":"http","x-forwarded-port":"80","host":"postman-echo.com","x-am
zn-trace-id":"Root=1-5f2ff376-881a8c584165f0f4bb5fe8a8","content-length":"46","user-agent":"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110
 Safari/537.36","accept-encoding":"gzip, deflate","accept":"application/json, text/javascript, */*; q=0.01","origin":"http://10.212.143.111","accept-language":"en-US,en;q=0.8","content-ty
pe":"application/json; charset=UTF-8","referer":"http://10.212.143.111/Ion/default.aspx","x-requested-with":"XMLHttpRequest","cookie":".APPLICATIONFRAMEWORK=D684EB482F28D2A34E3D3826125054
5C25D77913B62F7B5D275E9708FF97A0AED07EB8DDEF74798D85F51D588D1CB5D534C42620639C879A24514BEE36C87201F4D0835822EE7F; ASP.NET_SessionId=ee4a3gjs2dgyzgy3y3putp50"},"json":null,"url":"http://po
stman-echo.com/post"}
`

**Comment by verhovsky** [comment]
I think that this ANSI-C quoted string

> ```
> $'{\'subsKey\':\'x-pml:/diagrams/ud/network.dgm@\'}'
> ```

may've been what was causing the issue. If that's the case, this tracked in #207 and it should be fixed whenever the changes in #278 are deployed.
