### ISSUE TITLE
Add support for -X arguments not separated from the flag

### ISSUE THREAD

**Issue by loccs-spring** [NickCarneiro/curlconverter#83]
curl -XPUT 'localhost:9200/twitter/_mapping/user?pretty' -H 'Content-Type: application/json' -d'
{
  "properties": {
    "email": {
      "type": "keyword"
    }
  }
}
'

**Comment by wilsoff** [comment]
It works if you remove `-XPUT`

**Comment by NickCarneiro** [comment]
The issue here is that curl is very tolerant with respect to input. It will accept -XPUT or -XPOST instead of `-X PUT` or `-X POST`.

I'll add support for this.

**Comment by NickCarneiro** [comment]
fixed in 1.16.0
