### ISSUE TITLE
Extra white space between -H and the value of the header handled incorrectly

### ISSUE THREAD

**Issue by wilsoff** [NickCarneiro/curlconverter#84]
From the example post request, the following works fine:
`curl 'http://fiddle.jshell.net/echo/html/' -H 'Origin: http://fiddle.jshell.net' -H 'X-Requested-With: XMLHttpRequest' --data 'msg1=wow&msg2=such' --compressed`

Issue 1: Adding an extra space between `-H` and `'Orig...` causes the header to be omitted from the python result.  Same behaviour applies to _all but the final_ header value.

Issue 2: Adding an extra space between `-H` and `'X-Req...` causes the parser to fail altogether and reports '_Error parsing curl command._'   This behaviour only applies to the _final_ header value.

Suggestion: reduce all multiple spaces to single spaces before parsing.

**Comment by NickCarneiro** [comment]
Thanks for the descriptive steps to reproduce. This behavior is pretty bad. I'm surprised nobody else has noticed this.
