### ISSUE TITLE
Error in converting Curl Command to Node.js

### ISSUE THREAD

**Issue by vijay1anand** [NickCarneiro/curlconverter#88]
I have entered the following command and for converting it to node.js get the error 

> Error parsing curl command.

`curl -X POST -H "Content-Type: application/json" http://127.0.0.1:9000/sulekha/postprocessing -d  '{
  "needName" : "Maid Services",
  "commentID" :"1234",
  "comment": "Through this agency, I have got a good service."
}'`

**Comment by danpe91** [comment]
Hi @vijay1anand 

Where are you trying it? Can you explain the steps you are following to get the error?

I just tried cloning the repository, installing it from the npm modules and from the demo web site(https://curl.trillworks.com/) and it is working as expected with these 3 methods.

**Comment by vijay1anand** [comment]
Now it's working fine.
