### ISSUE TITLE
curl -F not correctly converted to POST request

### ISSUE THREAD

**Issue by nouser2013** [NickCarneiro/curlconverter#90]
As stated in the header, my CURL request is:
```curl -F "image=@image.jpg" http://server/targetservice```

It gets translated to: 
```
import requests
files = { 'image': ('image.jpg', open('image.jpg', 'rb')), }
response = requests.get('http://server/targetservice', files=files)
```

IMHO, last line should read:
```response = requests.get('http://server/targetservice', files=files)```

So, instead of a ```get```, requests should ```post``` the query.

**Comment by NickCarneiro** [comment]
Yeah, you're right. -F should be a post. This will be fixed in 1.15.0. Thanks for reporting.

From the manpage:

> -F, --form <name=content>
>               (HTTP) This lets curl emulate a filled-in form in which a user has pressed the submit button. This  causes  curl  to  POST  data
>               using the Content-Type multipart/form-data according to RFC 2388.
