### ISSUE TITLE
curl works at terminal CL, not in converter tool

### ISSUE THREAD

**Issue by colinkcurtis** [NickCarneiro/curlconverter#94]
Hello, the following command executes as expected at the terminal command line but will not convert at https://curl.trillworks.com/ :

`curl -X POST "http://127.0.0.1:6010/api/" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"machine_question\": {    \"edges\": [      {        \"source_id\": 0,        \"target_id\": 1      },      {        \"source_id\": 1,        \"target_id\": 2      }    ],    \"nodes\": [      {        \"curie\": \"MONDO:0005737\",        \"id\": 0,        \"name\": \"Ebola hemorrhagic fever\",        \"type\": \"disease\"      },      {        \"id\": 1,        \"type\": \"gene\"      },      {        \"id\": 2,        \"type\": \"genetic_condition\"      }    ]  }}"`

probably I am wrong but it told me to make an issue so here we are!!!

**Comment by daniellockard** [comment]
It looks like it works to me, now. Is it still broken for you @ColinKCurtis?

**Comment by NickCarneiro** [comment]
This seems to be working OK for me. What browser were you using?
