### ISSUE TITLE
Option for request data in dict instead of tuple

### ISSUE THREAD

**Issue by vivaelnino9** [NickCarneiro/curlconverter#96]
Hey! Love the site, use it almost every day! I was just wondering if there was any chance in the future that we can be given the option to instead have the converted request data in dict instead of tuple? I understand why tuple is used but I find myself having to convert the tuple to a dictionary for other non-related reasons and just thought it would be nice if an option was given. Thanks!

**Comment by NickCarneiro** [comment]
I have made dicts the new default when there are no duplicate keys in the payload. If the same key is used more than once it will use the list of tuples.

Change published in 2.1.0 and deployed to the demo site.

**Comment by vivaelnino9** [comment]
Looks great, Nick. Thanks!
