### ISSUE TITLE
Error parsing curl command.

### ISSUE THREAD

**Issue by rumo19** [NickCarneiro/curlconverter#98]
I want to run this curl command for salt-api . But showed that error

curl -kSs https://localhost:8000/login -H   'Accept: application/json' -d username=abcc -d password=abc123 -d eauth=pam

**Comment by NickCarneiro** [comment]
This is working for me in Chrome. What browser were you using?

**Comment by romadrutskii** [comment]
Couldn't reproduce the issue.
