### ISSUE TITLE
Interest in `Go` converter?

### ISSUE THREAD

**Issue by daniellockard** [NickCarneiro/curlconverter#99]
Hey! I know that curl-to-go exists, but are you interested in it here?

**Comment by NickCarneiro** [comment]
I think it would be pretty cool, but I don't have time to add it myself.

If you want to take a shot at it I'll accept a PR.

**Comment by daniellockard** [comment]
I'll gladly take a shot at it. I already took a bit of a run at it last night and I think I nearly have at least some basic support.

**Comment by NickCarneiro** [comment]
Reading the code now. Moving discussion to that PR if necessary.
